### ISSUE TITLE
Undo and clear board confirmation

### ISSUE THREAD

**Issue by erseco** [jmsaugar/fastboard.io.front#1]
Hello, I was testing your fastboard.io, and looks awesome!! I'm thinking of using it in class with students. For this, would be nice having an "undo" button as well as a confirmation screen previous to clear the screen.

Imagine a student in the class that clears all the drawings, that can be a problem!

Thanks!

**Comment by jmsaugar** [comment]
Hello,

Thanks for the feedback. Not the first time I have been asked for "undo" feature, so will probably implement it in the near future.

Regarding the board clearing confirmation, it is absolutely a good idea, so that will be coming sooner. Will keep you updated here.

Thanks!

**Comment by jmsaugar** [comment]
I just published online an update of the webapp containing some fixes, as well as the clear confirmation feature you suggested, so closing this issue. Not the "undo" feature for the moment, as it will take more time. Will let you know if it is released in the future!
