### ISSUE TITLE
Export don't work

### ISSUE THREAD

**Issue by GerSant** [jmsaugar/fastboard.io.front#3]
Export button "thinks" and show an error "There was an error exporting the board"

**Comment by jmsaugar** [comment]
Hello!

Thanks for the feedback. Could you give me some more details about it? What browser and version you were using would be of great help, as well as if it was on a mobile device, tablet or PC. It is a generic error shown when any of the steps of exporting fails, so I think it could probably be related to some specific browser or version incompatibility.
